from . import crm_claim_ept
from . import account_move
from . import stock_picking
from . import stock_warehouse
from . import stock_move
from . import sale_order
from . import repair_order
from . import res_config_settings
from . import crm_claim_line_ept
from . import crm_res_models
from . import stock_production_lot
