######################## Invoice ###############################
[{
    'sequence': 10,                         'sequence': 10,                             'sequence': 10,
    'discount': 0,                          'discount': 0,                              'discount': 0,
    'amount_currency': 0,                   'amount_currency': 0,                       'amount_currency': 0,
    'date_maturity': '2019-11-25',          'date_maturity': False,                     'date_maturity': False,
    'currency_id': False,                   'currency_id': False,                       'currency_id': False,
    'product_uom_id': False,                'product_uom_id': 1,                        'product_uom_id': False,
    'payment_id': False,                    'payment_id': False,                        'payment_id': False,
    'tag_ids': [[6, False, []]],            'tag_ids': [[6, False, []]],                'tag_ids': [[6, False, []]],
    'analytic_account_id': False,           'analytic_account_id': False,               'analytic_account_id': False,
    'analytic_tag_ids': [[6, False, []]],   'analytic_tag_ids': [[6, False, []]],       'analytic_tag_ids': [[6, False, []]],
    'display_type': False,                  'display_type': False,                      'display_type': False,
    'is_rounding_line': False,              'is_rounding_line': False,                  'is_rounding_line': False,
    'purchase_line_id': False,              'purchase_line_id': False,                  'purchase_line_id': False,
    'recompute_tax_line': False,            'recompute_tax_line': False,                'recompute_tax_line': False,
    'move_id': 239,                         'move_id': 239,                             'move_id': 239,
    'product_id': False,                    'product_id': 4,                            'product_id': False,
    'partner_id': 14,                       'partner_id': 14,                           'partner_id': 14,
    'exclude_from_invoice_tab': True,       'exclude_from_invoice_tab': False,          'exclude_from_invoice_tab': True,
    'tax_ids': [[6, False, []]],            'tax_ids': [[6, False, [2]]],               'tax_ids': [[6, False, []]],
    'quantity': 1,                          'quantity': 1,                              'quantity': 1,
    'price_unit': -81,                      'price_unit': 75,                           'price_unit': 6,
    'debit': 81,                            'debit': 0,                                 'debit': 0,
    'credit': 0,                            'credit': 75,                               'credit': 6,
    'name': False,                          'name': 'Design\nCustom Design',            'name': 'California %',
    'account_id': 83,                       'account_id': 81,                           'account_id': 81,
    'tax_repartition_line_id': False,       'tax_repartition_line_id': False,           'tax_repartition_line_id': 2,
    'tax_exigible': True,                   'tax_exigible': True,                       'tax_exigible': True,
    'tax_base_amount': 0,                   'tax_base_amount': 0,                       'tax_base_amount': 75,

}]

######################## Credit Note ###############################
[{
    'move_id': 540,                                     'move_id': 540,                     'move_id': 540,
    'account_id': 83,                                   'account_id': 1,                    'account_id': 1,
    'sequence': 10,                                     'sequence': 10,                     'sequence': 10,
    'name': '',                                         'name': 'California %',             'name': 'Hours',
    'quantity': 1.0,                                    'quantity': 1.0,                    'quantity': 1.0,
    'price_unit': -590.0,                               'price_unit': 40.0,                 'price_unit': 500.0,
    'discount': 0.0,                                    'discount': 0.0,                    'discount': 0.0,
    'debit': 0.0,                                       'debit': 40.0,                      'debit': 500.0,
    'credit': 590.0,                                    'credit': 0.0,                      'credit': 0.0,
    'amount_currency': 0.0,                             'amount_currency': 0.0,             'amount_currency': 0.0,
    'price_subtotal': -590.0,                           'price_subtotal': 40.0,             'price_subtotal': 500.0,
    'price_total': -590.0,                              'price_total': 40.0,                'price_total': 540.0,
    'blocked': False,                                   'blocked': False,                   'blocked': False,
    'date_maturity': datetime.date(2019, 11, 27),       'date_maturity': False,             'date_maturity': False,
    'currency_id': False,                               'currency_id': False,               'currency_id': False,
    'partner_id': 79,                                   'partner_id': 79,                   'partner_id': 79,
    'product_uom_id': False,                            'product_uom_id': False,            'product_uom_id': 1,
    'product_id': False,                                'product_id': False,                'product_id': 2,
    'tax_ids': [(6, 0, [])],                            'tax_ids': [(6, 0, [])],            'tax_ids': [(6, 0, [1])],
    'tax_base_amount': 0.0,                             'tax_base_amount': 500.0,           'tax_base_amount': 0.0,
    'tax_exigible': True,                               'tax_exigible': True,               'tax_exigible': True,
    'tax_repartition_line_id': False,                   'tax_repartition_line_id': 4,       'tax_repartition_line_id': False,
    'tag_ids': [(6, 0, [])],                            'tag_ids': [(6, 0, [])],            'tag_ids': [(6, 0, [])],
    'analytic_account_id': False,                       'analytic_account_id': False,       'analytic_account_id': False,
    'analytic_tag_ids': [(6, 0, [])],                   'analytic_tag_ids': [(6, 0, [])],   'analytic_tag_ids': [(6, 0, [])],
    'recompute_tax_line': False,                        'recompute_tax_line': False,        'recompute_tax_line': False,
    'display_type': False,                              'display_type': False,              'display_type': False,
    'is_rounding_line': False,                          'is_rounding_line': False,          'is_rounding_line': False,
    'exclude_from_invoice_tab': True,                   'exclude_from_invoice_tab': True,   'exclude_from_invoice_tab': False,
    'purchase_line_id': False,                          'purchase_line_id': False,          'purchase_line_id': False,
    'is_anglo_saxon_line': False                        'is_anglo_saxon_line': False        'is_anglo_saxon_line': False,
}]

[
{
  'account_id': 88,                     'account_id': 45,
  'sequence': 10,                       'sequence': 10,
  'name': False,                        'name': 'Gardening',
  'quantity': 1,                        'quantity': 1,
  'price_unit': 0,                      'price_unit': 200,
  'discount': 0,                        'discount': 0,
  'debit': 0,                           'debit': 200, 'credit': 0, 'amount_currency': 0, 'date_maturity': False, 'currency_id': False, 'partner_id': 128, 'product_uom_id': 1, 'product_id': 6, 'payment_id': False, 'tax_ids': [[6, False, []]], 'tax_base_amount': 0, 'tax_exigible': True, 'tax_repartition_line_id': False, 'tag_ids': [[6, False, []]], 'analytic_account_id': False, 'analytic_tag_ids': [[6, False, []]], 'recompute_tax_line': False, 'display_type': False, 'is_rounding_line': False, 'exclude_from_invoice_tab': False, 'purchase_line_id': False, 'move_id': 546}, {'account_id': 88, 'sequence': 10, 'name': False, 'quantity': 1, 'price_unit': -200, 'discount': 0, 'debit': 0, 'credit': 200, 'amount_currency': 0, 'date_maturity': '2019-11-27', 'currency_id': False, 'partner_id': 128, 'product_uom_id': False, 'product_id': False, 'payment_id': False, 'tax_ids': [[6, False, []]], 'tax_base_amount': 0, 'tax_exigible': True, 'tax_repartition_line_id': False, 'tag_ids': [[6, False, []]], 'analytic_account_id': False, 'analytic_tag_ids': [[6, False, []]], 'recompute_tax_line': False, 'display_type': False, 'is_rounding_line': False, 'exclude_from_invoice_tab': True, 'purchase_line_id': False, 'move_id': 546}]
  'credit': 0,
  'amount_currency': 0,
  'date_maturity': '2019-11-27',
  'currency_id': False,
  'partner_id': 128,
  'product_uom_id': False,
  'product_id': False,
  'payment_id': False,
  'tax_ids': [[6, False, []]],
  'tax_base_amount': 0,
  'tax_exigible': True,
  'tax_repartition_line_id': False,
  'tag_ids': [[6, False, []]],
  'analytic_account_id': False,
  'analytic_tag_ids': [[6, False, []]],
  'recompute_tax_line': False,
  'display_type': False,
  'is_rounding_line': False,
  'exclude_from_invoice_tab': True,
  'purchase_line_id': False,
  'move_id': 546

